/** All 77 Thai provinces, grouped for list-property dropdowns. */
export const THAI_PROVINCE_GROUPS = [
  {
    label: 'North',
    provinces: [
      'Chiang Mai',
      'Chiang Rai',
      'Lampang',
      'Lamphun',
      'Mae Hong Son',
      'Nan',
      'Phayao',
      'Phrae',
      'Uttaradit',
    ],
  },
  {
    label: 'Northeast',
    provinces: [
      'Amnat Charoen',
      'Bueng Kan',
      'Buri Ram',
      'Chaiyaphum',
      'Kalasin',
      'Khon Kaen',
      'Loei',
      'Maha Sarakham',
      'Mukdahan',
      'Nakhon Phanom',
      'Nakhon Ratchasima',
      'Nong Bua Lamphu',
      'Nong Khai',
      'Roi Et',
      'Sakon Nakhon',
      'Si Sa Ket',
      'Surin',
      'Ubon Ratchathani',
      'Udon Thani',
      'Yasothon',
    ],
  },
  {
    label: 'Central',
    provinces: [
      'Ang Thong',
      'Chai Nat',
      'Kamphaeng Phet',
      'Lop Buri',
      'Nakhon Nayok',
      'Nakhon Pathom',
      'Nakhon Sawan',
      'Nonthaburi',
      'Pathum Thani',
      'Phichit',
      'Phitsanulok',
      'Phra Nakhon Si Ayutthaya',
      'Phetchabun',
      'Samut Prakan',
      'Samut Sakhon',
      'Samut Songkhram',
      'Saraburi',
      'Sing Buri',
      'Sukhothai',
      'Suphan Buri',
      'Uthai Thani',
    ],
  },
  {
    label: 'East',
    provinces: [
      'Chachoengsao',
      'Chanthaburi',
      'Chon Buri',
      'Prachin Buri',
      'Rayong',
      'Sa Kaeo',
      'Trat',
    ],
  },
  {
    label: 'West',
    provinces: [
      'Kanchanaburi',
      'Phetchaburi',
      'Prachuap Khiri Khan',
      'Ratchaburi',
      'Tak',
    ],
  },
  {
    label: 'South',
    provinces: [
      'Chumphon',
      'Krabi',
      'Nakhon Si Thammarat',
      'Narathiwat',
      'Pattani',
      'Phang Nga',
      'Phatthalung',
      'Phuket',
      'Ranong',
      'Satun',
      'Songkhla',
      'Surat Thani',
      'Trang',
      'Yala',
    ],
  },
  {
    label: 'Bangkok',
    provinces: ['Bangkok (Krung Thep Maha Nakhon)'],
  },
] as const

export const THAI_PROVINCES = THAI_PROVINCE_GROUPS.flatMap((group) => [...group.provinces])
